### ISSUE TITLE
Implement quantile approximation

### ISSUE THREAD

**Issue by aimalz** [aimalz/qp#1]
@drphilmarshall I have code that does some of this but it needs to be integrated into the qp class. This is an Epic, being addressed in PR #2 .

* [x] `PDF.quantize()` #14 
* [x] `PDF.interpolate()` #15 
* [x] KL divergence between PDF and qp approximation #9 
* [x] 'PDF.histogram()' #23 
* [x] Better quantile spacing #35

**Comment by drphilmarshall** [comment]
Since #16 you can check off the top item on your Epic list, @aimalz . Next item of business is #15, I guess? Looking fwd to seeing the plot in the demo! :-)

**Comment by aimalz** [comment]
How are we doing on today's launch deadline?  I'm not sure what we need to do to execute a launch.  Is the basic goal to make it PyPI/pip installable?  (Is it even ready for that?)

**Comment by drphilmarshall** [comment]
This issue can be closed, because I punted #24 to the future. The only remaining issue in the milestone is the KLD notebook, #34 - once you have done that, there's no more development to be done and you can make a "release". Call it "v0.1" and "beta"  or something - "beta" implies its ready for others to use, and I think it is! :-) Just make sure that the version number in `setup.py` matches whatever you choose. I'd avoid v1.0 until we have a Note done. (At the moment the _method_ is not fully tested!) What do you think?

**Comment by drphilmarshall** [comment]
PS. Here's the milestone: https://github.com/aimalz/qp/milestone/1
