### ISSUE TITLE
Add to the KLD notebook derivations of Gaussian behavior

### ISSUE THREAD

**Issue by aimalz** [aimalz/qp#34]
This is a continuation of @drphilmarshall's suggestion in #30.

**Comment by drphilmarshall** [comment]
Let's add this to `kld.ipynb`.

@aimalz You pointed me to [this webpage](http://stats.stackexchange.com/questions/7440/kl-divergence-between-two-univariate-gaussians) - looking at this, it turns out my algebra was not very far off at all! With a bit more re-arranging I think you should be able to make a link to the precision ratio $\sigma/\sigma_0$ and tension parameter. 

To whit: note that 

$ \sigma_2^2 = \frac{ \left(  \sigma_1^2 +  \sigma_2^2 \right) }{ \sigma_1^2 \left( \frac{1}{\sigma_1^2} +  \frac{1}{\sigma_2^2} \right)}$

This should leave you with an expression that includes a term 

$ \frac{1}{2} \left( 1 + \frac{\sigma_1^2}{\sigma_2^2} \right) \frac{\left( \mu_1 - \mu_2 \right)^2}{\left( \sigma_1^2 +  \sigma_2^2 \right)} $

So we still have two useful summary statistics, the precision ratio $r = \sigma_2 / \sigma_1$, and the tension $t$ where $t^2 = \frac{\left( \mu_1 - \mu_2 \right)^2}{\left( \sigma_1^2 +  \sigma_2^2 \right)} $ . I think I get that 

$ D = \log{r}  -  \frac{1}{2} \left( 1 - 1/r^2 \right) + \frac{1}{2} \left( 1 + 1/r^2 \right) t^2$

Do you agree? (All this will be easier to read once you paste it into the notebook and check it! :-) )

**Comment by drphilmarshall** [comment]
I'd then suggest that we use this analytic model in the plots, using a quick `def` in the notebook, and labeling it "Analytic" or "Model" or somesuch. You should point out that we are effectively doing a functional test of the KLD code in this way.
