### ISSUE TITLE
Comprehensive test suite

### ISSUE THREAD

**Issue by drphilmarshall** [aimalz/qp#36]
@aimalz I think for a good LSST DESC Note we'll need to do a fairly comprehensive suite of tests. We want to find efficient PDF characterizations that can cope robustly with randomly drawn multi-modal distributions, right? Maybe you can come up with a scheme that generates plausible photo-z-like PDFs, so that we can do more interesting comparisons between characterizations. I think the KLD will be a good metric for comparison, but we do want to explore where each characterization fails... Maybe we can discuss this a bit here before starting a big notebook (that will become our DESC Note)?

**Comment by aimalz** [comment]
I propose making a model for photo-z PDFs based on a z_spec vs. z_phot plot (which seem to be standard, see Figs. 12 and 14 [here](https://arxiv.org/pdf/1008.0658.pdf) for example).  We could make a continuous version by fitting a mixture of bivariate Gaussians to the output of an actual photo-z code in this format.  Constant z_phot cuts through the plot correspond to realistic photo-z PDFs to use as the "truth" for a mock survey of `qp` `PDF` objects that could be used in testing for a science case.  Edit: It should be noted that to make plots like that for a photo-z PDF method , the datapoints must represent samples from the PDFs, not just peak values or some other point estimator derived from PDFs.

**Comment by drphilmarshall** [comment]
Sounds good. Can you get a reasonable LSST ugrizy zp-zs scatter plot
forecast dataset from the LSST DESC PZ WG? I'm sure @sschmidt23 has one
lying around just next to his right elbow :-)

**Comment by sschmidt23** [comment]
Sorry, I forgot to answer this.  As a place to start, I'll give you both point photo-z's and full p(z)'s for a set of 111k galaxies from the photo-z DC1 Buzzard dataset that I created with a run of BPZ.  This is probably not a dataset that you'll want to use as the final dataset (I say that because the QQ plots that I made for redshift slices seemed to show some biases in the p(z)'s that BPZ predicted, while other methods seemed to be a little less biased, but I only have my BPZ run on hand right now).  But, hopefully it will get you started, and once we get updated results from ANNz2 or sparseGP or some other photo-z code, you can use those results instead.

For now I've just put a few files on dropbox here:
https://www.dropbox.com/sh/70104xhp01mm9zn/AAB3JYCGMwT_KeItsHYhZTKBa?dl=0
The fits file contains the id, ra, dec, specz, ugrizy mags+errors, etc...
-test_magscat_trainingfile.bpz contains the id, point photo-z estimate (Z_B, 2nd column), true redshift (SZ, 10th column) and some other columns that you'll see labeled at the top of the file.  i-band magnitude is called "MAG" and is in the 11th column.  Note that this data goes to i<26.9, so you'll probably want to cut this back to something more like i<25.3 "gold sample" so as not to include the really bad photo-z's for faint galaxies.
-test_magscat_trainingfile_probs.out contains the marginalized p(z) for each object in the fits file/BPZ file, where the values are for a redshift grid given by z=numpy.arange(0.005,2.11,0.01)

Let me know if you have any questions, and if this data suits your needs.

**Comment by drphilmarshall** [comment]
Thanks Sam, this is *great* :-) While you were pulling this together, we
got put in touch with Melissa Graham, who gave us a similar but smaller,
and private, dataset, from her own work for the Project: it's nice to work
on that because she'll be able to relate our results directly to her own.
However, a bigger, public sample with different properties from you is most
welcome - we'll check it out and let you know how we get on. Thank you!
